### ISSUE TITLE
Number of Days between

### ISSUE THREAD

**Issue by sean-hill** [JerrySievert/date-utils#49]
Lets say we have March 12th as a date and March 20th. Technically the number of days between these two days is 7, as the library returns. In my mind however it seems like it should be 8 days. For instance lets say I was using this to pay bills. I want to tell my clients I will be paying their bills on the 20th which to them is "8 days from now", however the library returns 7. Should I just do

    var daysBetween = d1.getDaysBetween(d2) + 1

To simulate this experience?

**Comment by sean-hill** [comment]
Oh weird,

So a date set at March 12th and a date set at March 18th returns 6 days in between them.
And a date set at March 12th and a date set at March 19th returns 6 days in between them.

How is this possible?

**Comment by sean-hill** [comment]
I keep getting this same problem, where the `getDaysBetween` function keeps returning different numbers, like it alternates between 2 and 3 for a date 3 days from now.

**Comment by sean-hill** [comment]
Whoops, accidentally closed this...

**Comment by JerrySievert** [comment]
do you have a code snippet that you can share that shows the problem?

the function itself is pretty braindead simple:

```js
function (date) {
   return ((date.clone().valueOf() - this.valueOf()) / 86400000) | 0;
}
```
