### ISSUE TITLE
Property 'jui' redefine problem

### ISSUE THREAD

**Issue by starlight36** [JerrySievert/date-utils#57]
I'm using date-utils in my react native project. After I upgrade the date-utils to the latest version, my project is keeping crash. From the log info, I got a message:

> Attempted to redefine property 'jui'

Then I located the problem in date-utils, the code:

[https://github.com/JerrySievert/date-utils/blob/master/lib/date-utils.js#L1722](https://github.com/JerrySievert/date-utils/blob/master/lib/date-utils.js#L1722)

```
monthNames = {
    'jan': 0,
    'janvier': 0,
    'fév': 1,
    'février': 1,
    'mar': 2,
    'mars': 2,
    'avr': 3,
    'avril': 3,
    'mai': 4,
    'jui': 5,
    'juin': 5,
    'jui': 6,
    'juillet': 6,
    'aoû': 7,
    'août': 7,
    'sep': 8,
    'septembre': 8,
    'oct': 9,
    'octobre': 9,
    'nov': 10,
    'novembre': 10,
    'déc': 11,
    'décembre': 11
};
```

The property `jui` is redefined. Is any better way to realize this month names define?

This problem appears after v1.2.16.

**Comment by JerrySievert** [comment]
thanks - i will take a look
