### ISSUE TITLE
getMonthsBetween inconsitency

### ISSUE THREAD

**Issue by sean-hill** [JerrySievert/date-utils#60]
I'm confused to the fact why this returns two separate results.

	> var now = new Date()
	> var twoMonths = new Date().addMonths(2)
	> now.getMonthsBetween(twoMonths)
	2.033333333333333
	> twoMonths.getMonthsBetween(now)
	1.0333299999999999

I assume they'd be the same with a result of 2.

**Comment by JerrySievert** [comment]
That's a darned good question.

**Comment by JerrySievert** [comment]
i'll try to dig into this soon - i was working on another project most of the weekend, and ran out of time.

**Comment by sean-hill** [comment]
Thanks Jerry :)

-- 
Sean Hill
me@seanhill.info
www.seanhill.info

On April 18, 2016 at 8:57:59 AM, Jerry Sievert (notifications@github.com) wrote:

i'll try to dig into this soon - i was working on another project most of the weekend, and ran out of time.

**Comment by JerrySievert** [comment]
it looks like this method could be rewritten fairly easily to be a lot more accurate.

i'll take a quick pass at it this evening, and if i get it working will get it updated.

might not be until this weekend until it's fixed, depends on how much free time i'm able to get.

**Comment by JerrySievert** [comment]
i rewrote `getMonthsBetween` to be a lot more precise than what was there:

```js
      var daysDiff = Math.abs(((+this) / (86400 * 1000)) - ((+date) / (86400 * 1000)));
      var start = new Date((+date) < (+this) ? (+date) : (+this));
      var end = new Date((date) > (+this) ? (+date) : (+this));

      var months = 0;
      while (+start < +end) {
        months++;
        start = start.addMonths(1);
      }

      var days = Math.abs(((+start) / (86400 * 1000)) - ((+end) / (86400 * 1000)));

      return months - (days / 31);
```

i've published a new release.

**Comment by sean-hill** [comment]
Thanks Jerry! :thumbsup:

**Comment by JerrySievert** [comment]
it was actually done 6 days ago, but i just found that i hadn't hit "comment" on the comment.
